### ISSUE TITLE
Build Watson Fails with Unicode Encode Error

### ISSUE THREAD

**Issue by crackjack** [etianen/django-watson#101]
I have a weird issue where my search results shows only objects instead of title for a particular content type. I have attached a screenshot for this issue.

![search results django watson](https://cloud.githubusercontent.com/assets/191368/6680933/8a4ec820-cc86-11e4-8824-73fddab4cda6.png)

I thought, rebuilding watson may solve the issue and tried to rebuild it. But I got Unicode Encode Error. 

I visited the issues section, and found a similar issue, so, I updated my django-watson version, it is now 1.1.5, which is the latest according to github releases, but I still get the same error.

``` Python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 117, in handle
    refreshed_model_count += rebuild_index_for_model(model, engine_slug, verbosity)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 50, in rebuild_index_for_model
    _bulk_save_search_entries(iter_search_entries())
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 172, in _bulk_save_search_entries
    search_entry_batch = list(islice(search_entries, 0, batch_size))
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 35, in iter_search_entries
    for search_entry in search_engine_._update_obj_index_iter(obj):
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 439, in _update_obj_index_iter
    "title": adapter.get_title(obj),
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 96, in get_title
    return force_text(obj)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0101' in position 36: ordinal not in range(128)
```

Then I read a post in Quora about setting python environment variable as follows:

    export PYTHONIOENCODING=utf-8

After that, rebuilding took a while, eventually failing again with a different character and position

``` Python
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/db/transaction.py", line 399, in inner
    return func(*args, **kwargs)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 117, in handle
    refreshed_model_count += rebuild_index_for_model(model, engine_slug, verbosity)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 50, in rebuild_index_for_model
    _bulk_save_search_entries(iter_search_entries())
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 172, in _bulk_save_search_entries
    search_entry_batch = list(islice(search_entries, 0, batch_size))
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 35, in iter_search_entries
    for search_entry in search_engine_._update_obj_index_iter(obj):
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 439, in _update_obj_index_iter
    "title": adapter.get_title(obj),
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/watson/registration.py", line 96, in get_title
    return force_text(obj)
  File "/home/edusanjal/public_html/beta/env/lib/python2.7/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 37: ordinal not in range(128)
```

Please help me solve this issue.

Regards.

**Comment by etianen** [comment]
One of your model __unicode__ methods is returning a str, rather than a unicode. Fix that, and everything will work.

**Comment by crackjack** [comment]
I had few characters in my data, which was not unicode, had to remove them manually and the build worked.
