### ISSUE TITLE
buildwatson - watson.registration.SearchAdapterError behind two related fields

### ISSUE THREAD

**Issue by bykof** [etianen/django-watson#110]
Hello etianen,

I love watson, it is great and fast. But since my last deployment I have a big problem.
My problem is that I have a model which have a Foreignkey on another model. But I would like to search in this "another" model. The problem is that this "another" model can be null.
So this type of register doesn't work: 
```
watson.register(
    ServiceInvoiceCase,
    fields=(
        'pj_invoice__pj_customer__name',
        'pj_invoice__pj_customer__customer_id',
    ),
)
```

I get this error
```
watson.registration.SearchAdapterError: Could not find a property called u'pj_customer' on either <PjInvoice: 615> or <watson.registration.CustomSearchAdapter object at 0x107e01dd0>
```

Can you help me please? 
Thank you very much!

**Comment by etianen** [comment]
Are you using version 1.1.7? I believe a fix for this was put in.

**Comment by bykof** [comment]
Yes I am using 1.1.7, 
I done ./manage.py uninstallwatson
then deleted the table watson_searchentry
after that i do a syncdb
then I done ./manage.py installwatson
then again ./manage.py buildwatson and the same error comes again :(

**Comment by etianen** [comment]
Annoying. Can I have a full stack trace. I’m sure there’s an easy fix here.

**Comment by bykof** [comment]
Sure, here you go :) 

```
Traceback (most recent call last):
  File "src/manage_local.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 122, in handle
    refreshed_model_count += rebuild_index_for_model(model, engine_slug, verbosity)
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 54, in rebuild_index_for_model
    _bulk_save_search_entries(iter_search_entries())
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 175, in _bulk_save_search_entries
    search_entry_batch = list(islice(search_entries, 0, batch_size))
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 39, in iter_search_entries
    for search_entry in search_engine_._update_obj_index_iter(obj):
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 444, in _update_obj_index_iter
    "content": adapter.get_content(obj),
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 129, in get_content
    for field_name in field_names
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 129, in <genexpr>
    for field_name in field_names
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 78, in _resolve_field
    return self._resolve_field(value, name_parts[1])
  File "/Users/mbykovski/Documents/workspace/connect/virtualenv/lib/python2.7/site-packages/watson/registration.py", line 72, in _resolve_field
    search_adapter = self,
watson.registration.SearchAdapterError: Could not find a property called u'pj_customer' on either <PjInvoice: 8914> or <watson.registration.CustomSearchAdapter object at 0x112170f10>

```

**Comment by etianen** [comment]
I don’t think that this is a bug in django-watson.

Apparently, PjInvoice does not have a field called pj_customer.

**Comment by bykof** [comment]
Hi etianen,
unfortunately this is not true. My model PjInvoice definitely has the field pj_customer.
I will look through your code and try to fix this issue. Then I will create a pull request. Thanks in advance for your help.

**Comment by bykof** [comment]
@etianen I think the problem is that django_watson tries to resolve the second related field and if it doesn't exist he drops the excpetion. However I will try to fix it.
