### ISSUE TITLE
Search for string beginning with apostrophe breaks watson (at least) on Postgres

### ISSUE THREAD

**Issue by JirkaV** [etianen/django-watson#112]
This is straight copy of https://groups.google.com/forum/#!topic/django-watson/PN1mkiBnQCc so it's not lost :)

> ...
> tried to replicate the problem and found out that I'm getting ProgrammingError just by searching for a common word preceded by an apostrophe, e.g.  'hello
>
>  For the record, my DB is Postgres 9.3, Django 1.7 and watson 1.1.5 (upgrade to 1.1.7 didn't help). The error I'm getting is
>
```
 syntax error in tsquery: "''hello:*"
```

Here is a fix that works for me, but as mentioned, I'm having trouble running watson's test suite so can't test it properly:

> "fix" is simple change to backends.make_escaper(). Changing the apostrophe handler fixes things for me. Take it with a grain of salt though.

```
    translation_table[ord("'")] = r"\''"
```

**Comment by etianen** [comment]
I'm having a hard time recreating your bug.

https://travis-ci.org/etianen/django-watson

Could you try to updating the test case to recreate your issue?

https://github.com/etianen/django-watson/blob/master/src/tests/test_watson/tests.py#L295

**Comment by JirkaV** [comment]
Finally got around testing this, sorry. 

Indeed, the default test suite runs fine on SQLite3. However changing runtests.py to use PostgreSQL database throws the following:
```
Creating test database for alias 'default'...
.............................EE................EE....
======================================================================
ERROR: testSearchWithLeadingApostrophe (tests.test_watson.tests.LiveFilterSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jirka/dev/django-watson/src/tests/test_watson/tests.py", line 301, in testSearchWithLeadingApostrophe
    self.assertEqual(watson.search("'content").count(), 1)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 318, in count
    return self.query.get_count(using=self.db)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 445, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: syntax error in tsquery: "''content:*"


======================================================================
ERROR: testSearchWithLeadingApostrophe (tests.test_watson.tests.LiveFilterSearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jirka/dev/django-watson/src/tests/test_watson/tests.py", line 120, in tearDown
    WatsonTestModel1.objects.all().delete()
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 536, in delete
    collector.collect(del_query)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 197, in collect
    reverse_dependency=reverse_dependency)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/deletion.py", line 97, in add
    if not objs:
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 170, in __nonzero__
    return type(self).__bool__(self)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jirka/.virtualenvs/apostrophe/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by etianen** [comment]
Oh, goodness, I just realised that when I made the tests run on Django 1.8, I hardcoded it to always use sqlite as a database backend. Big fail.

I'll look into this when I'm back from holiday, next week.

**Comment by etianen** [comment]
The latest push to master should have addressed the issue. Please take a look, and let me know what you think!

**Comment by JirkaV** [comment]
Works for me, thank you!

**Comment by bee-keeper** [comment]
Hi, I just cloned the repo and found this test still failing when running against PostgreSQL 9.4.4

```
======================================================================
ERROR: testSearchWithLeadingApostrophe (tests.test_watson.tests.SearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/WebServer/Documents/watson/src/tests/test_watson/tests.py", line 312, in testSearchWithLeadingApostrophe
    self.assertTrue(watson.search("'content").exists())  # Some database engines ignore leading apostrophes, some count them.
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/query.py", line 606, in exists
    return self.query.has_results(using=self.db)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/sql/query.py", line 457, in has_results
    return compiler.has_results()
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 758, in has_results
    return bool(self.execute_sql(SINGLE))
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: syntax error in tsquery: "''content:*"


======================================================================
ERROR: testSearchWithLeadingApostrophe (tests.test_watson.tests.SearchTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/WebServer/Documents/watson/src/tests/test_watson/tests.py", line 115, in tearDown
    WatsonTestModel1.objects.all().delete()
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/query.py", line 556, in delete
    collector.collect(del_query)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/deletion.py", line 168, in collect
    reverse_dependency=reverse_dependency)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/deletion.py", line 79, in add
    if not objs:
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/query.py", line 145, in __nonzero__
    self._fetch_all()
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 701, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 787, in execute_sql
    cursor.execute(sql, params)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/fluffikins/.virtualenvs/united2/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

**Comment by etianen** [comment]
The Travis CI tests are running 9.1, and they report success.

https://travis-ci.org/etianen/django-watson/jobs/79171627

My local machine is running 9.4.4, and it reports success too.

I'm not sure what to suggest...

**Comment by etianen** [comment]
Hmm, are you using the master branch?

**Comment by bee-keeper** [comment]
Hi there, I found the issue is related to Postgres on OSX.  Test passes on Postgres on Ubuntu.
