### ISSUE TITLE
Getting started with django-watson: fail

### ISSUE THREAD

**Issue by ppython** [etianen/django-watson#189]
Hello,

Just trying to test django-watson on a project, followed the [getting-started procedure](https://github.com/etianen/django-watson/wiki#getting-started-with-django-watson):
- 👍  installed with pip
- 👍 watson added to my django INSTALLED_APPS settings
- 👍  'syncdb' does not apply (and makemigrations does not find changes)
- 👎  'installwatson' : So it's where the problems begins (I also tried the build command):

`(virtenv)hello@world:~/projects/mybeautifulproject$ ./manage.py installwatson --verbosity 3
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/watson/management/commands/installwatson.py", line 25, in handle
    backend.do_install()
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/watson/backends.py", line 229, in do_install
    search_config=self.search_config
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/hello/virtualenvs/mybeautifulproject/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "watson_searchentry" does not exist
`

My env:
- python: 2.7.6 
- Django: 1.10
- Pip: pip 1.5.4
- Virtualenv: 1.11.4
- django-watson: 1.2.4

Any ideas before digging farther?

**Comment by amureki** [comment]
@ppython did you try to run `migrate` manage.py command? Because `syncdb` was deprecated in Django, so if you are using Django 1.10, you have to run all migrations via `migrate`.

**Comment by ppython** [comment]
Indeed!
`(virtenv)hello@world:~/projects/mybeautifulproject$ ./manage.py showmigrations
watson
 [ ] 0001_initial
`

'makemigrations', didn't produce results because there is already [the initial watson migration] file present (https://github.com/etianen/django-watson/blob/master/watson/migrations/0001_initial.py)!

I just [updated the wiki](https://github.com/etianen/django-watson/wiki/Home/_compare/35fdeebe860f8529f4157520e79e39c4783431d1...c0f2206fe306dd935b4f352f6dd309a59dee312c) steps to reflect this change ;)

**Comment by etianen** [comment]
Thanks!
