### ISSUE TITLE
AttributeError: 'module' object has no attribute 'register'

### ISSUE THREAD

**Issue by huangzhongkai** [etianen/django-watson#192]
hi,
i have a issue with the django-1.6.8;

*Traceback : *

> Traceback (most recent call last):
  File "/Users/huangzhongkai/company_code/Pro2.0/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Library/Python/2.7/site-packages/django/core/management/base.py", line 280, in execute
    translation.activate('en-us')
  File "/Library/Python/2.7/site-packages/django/utils/translation/__init__.py", line 130, in activate
    return _trans.activate(language)
  File "/Library/Python/2.7/site-packages/django/utils/translation/trans_real.py", line 188, in activate
    _active.value = translation(language)
  File "/Library/Python/2.7/site-packages/django/utils/translation/trans_real.py", line 177, in translation
    default_translation = _fetch(settings.LANGUAGE_CODE)
  File "/Library/Python/2.7/site-packages/django/utils/translation/trans_real.py", line 159, in _fetch
    app = import_module(appname)
  File "/Library/Python/2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/corsheaders/__init__.py", line 1, in <module>
    from .checks import check_settings  # noqa: F401
  File "/Library/Python/2.7/site-packages/corsheaders/checks.py", line 14, in <module>
    @checks.register
AttributeError: 'module' object has no attribute 'register'

check.py
>from django.core import checks
@checks.register
def check_settings(app_configs, **kwargs):
      pass

Any help would be appreciated, thank you very much :)

**Comment by etianen** [comment]
It looks like a 3rd party package called corsheaders is not compatible with
django 1.6.8. This appears unrelated to django-watson.
