### ISSUE TITLE
Unicode errors when building the index with verbosity other then default

### ISSUE THREAD

**Issue by thedrow** [etianen/django-watson#88]
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/django/db/transaction.py", line 431, in inner
    return func(*args, **kwargs)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 117, in handle
    refreshed_model_count += rebuild_index_for_model(model, engine_slug, verbosity)
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 50, in rebuild_index_for_model
    _bulk_save_search_entries(iter_search_entries())
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/watson/registration.py", line 172, in _bulk_save_search_entries
    search_entry_batch = list(islice(search_entries, 0, batch_size))
  File "/usr/local/share/.virtualenvs/django.zcloud.vnv/lib/python2.7/site-packages/watson/management/commands/buildwatson.py", line 42, in iter_search_entries
    engine_slug = engine_slug_,
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 37: ordinal not in range(128)
```
I'm not sure what's the value that it's failing on but it seems that the print statement should encode everything to unicode.

**Comment by etianen** [comment]
I’ve just pushed something to master that might help.

**Comment by thedrow** [comment]
Yup that should do it.
Let's do the same for the engine slug in case anyone uses a slug that isn't unicode.

**Comment by etianen** [comment]
More in master for this now. I think I got everything that could cause unicode errors.

**Comment by thedrow** [comment]
Yup that does it.
Thanks.
